### ISSUE TITLE
Triangle select background not transparent

### ISSUE THREAD

**Issue by naxvog** [taniarascia/primitive#27]
Currently if you alter the background color of a select element you will see that the used triangle background has itself a white background. It would be nice to have a transparent background image instead.

Tinkered a bit and I am currently using this:
```css
select {
   background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAAJCAYAAAA/33wPAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAjklEQVQoz5XPMQrCQBBG4W8TBLHXowiewHt4HDvtbDxD7LSy0yvYClZia7CKNlssATfJD8vMMG8fuwF7LORzxSoHFFijyTBNZHSJbqgyTBWZbEKsM5wwbu0/WOLZJSpjfWOEeWu/w1mPhKSf4IhpnF/xNXUfUZH0NbbJvOkr+ffVQzzl0ItpvnjggvsQ0Q+efRi5Tqrz0wAAAABJRU5ErkJggg==);
}
```
